### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [anadon/hmmer2#1]
Hi,
please help users and distributers spotting releases (in contrast to random development commits) by using release tags.
Kind regards, Andreas.

**Comment by anadon** [comment]
I thought I added tags in git.  Can you send me a reference to read up on
for what you want?

**Comment by tillea** [comment]
On Thu, Nov 01, 2018 at 05:55:45AM -0700, jrmarsha wrote:
> I thought I added tags in git.  Can you send me a reference to read up on
> for what you want?
That page should not be empty:
    https://github.com/anadon/hmmer2/releases

**Comment by anadon** [comment]
https://github.com/MichiganTech/hmmer/releases

**Comment by tillea** [comment]
On Thu, Nov 01, 2018 at 07:50:59PM +0000, jrmarsha wrote:
> https://github.com/MichiganTech/hmmer/releases
Thanks.  Feel free to close this issue.  I've pointed the Debian watch file in packaging Git to this location but I can ot promise any upload in November.

**Comment by anadon** [comment]
Thanks!  My thing isn't that it gets done soon, just at all.
